# Generated by Django 5.2.7 on 2025-10-02 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_prueba",
                    models.CharField(
                        choices=[
                            ("traccion", "Tracción"),
                            ("compresion", "Compresión"),
                            ("dureza", "Dureza"),
                            ("fatiga", "Fatiga"),
                            ("flexion", "Flexión"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("resultados", models.JSONField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_materials.material",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
